config/routes.rb
DrPicasa::Application.routes.draw do
  get 'login' => "auth#login"
  get 'callback' => "auth#callback"

  root :to => "albums#index", :as => 'albums'
  get ':id' => "albums#show", :as => 'album'
  get ':photo_id/comments' => "albums#comments"
  post ':photo_id/comments' => "albums#comment"
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # rescue_from Exception, :with => :error_render_method
  before_filter :ensure_token

  def index
    @albums = Picasa.albums(session[:token])
  end

  def show
    @album = Picasa.photos(session[:token], params[:id])
  end

  def comments
    @photo = Picasa.comments(session[:token], params[:album_id], params[:photo_id])
    render :layout => false
  end

  def comment
    @comment = Picasa.add_comment(session[:token], params[:comment][:album_id], params[:comment][:photo_id], params[:comment][:text])
  end

  def ensure_token
    redirect_to :action => :login, :controller => :auth unless session[:token]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  include PicasaAuth

  def login
    redirect_to oauth_client.auth_code.authorize_url(
      :scope => "http://picasaweb.google.com/data/",
      :access_type => "offline",
      :redirect_uri => "http://#{request.host_with_port}/callback",
      :approval_prompt => 'force')
  end

  def callback
    access_token_obj = oauth_client.auth_code.get_token(params[:code],
      :redirect_uri =>  "http://#{request.host_with_port}/callback",
      :token_method => :post)
    session[:token] = {
      :access_token => access_token_obj.token,
      :refresh_token => access_token_obj.refresh_token
    }
    puts session[:token]
    redirect_to :controller => :albums, :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_comment.html.haml
.well
  = comment[:content]
  .row
    %i.pull-right
      = comment[:author]

app/views/albums/comment.js.erb
 <%-text = render :partial => 'comment', :locals => {:comment => @comment}%>
$('#comments').append($("<%=j text%>"))
$('form#comment button').removeClass('disabled')
$('form#comment button').attr('disabled', false)
$('form#comment textarea').val('')

app/views/albums/comments.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
  %h3
    = @photo[:title]
.modal-body
  .row-fluid
    .span7
      =image_tag @photo[:url], :class => 'photo'
    .span5
      #comments
        - @photo[:comments].each do |comment|
          = render :partial => 'comment', :locals => {:comment => comment}
      .well
        = form_for :comment, :remote => true, :html => {:id => 'comment'} do |f|
          = f.hidden_field :photo_id, :value => @photo[:id]
          = f.hidden_field :album_id, :value => @photo[:album_id]
          = f.text_area :text, :placeholder => "Type in your message", :rows => 5, :required => true, :maxlength => 320
          .row-fluid
            %button.btn.btn-info{:type => "submit"} Post New Message
.modal-footer

app/views/albums/index.html.haml
%ul.inline
  - @albums.each do |album|
    %li
      = link_to album_path(album[:id]), :class => 'thumbnail' do
        = image_tag album[:thumbnail]#, :class => "img-polaroid"
        .caption
          %h5
            = album[:title]
/ %ul.thumbnails
/ - @albums.each do |album|
/   %li.span2
/     = link_to album_path(album[:id]), :class => 'thumbnail' do
/       = image_tag album[:thumbnail]#, :class => "img-polaroid"
/       .caption
/         %h5
/           = album[:title]

app/views/albums/show.html.haml
%i
  = link_to '←', '/'
%h2
  = @album[:title]
%ul.inline{:'data-id' => @album[:id]}
  - @album[:photos].each do |photo|
    %li
      = link_to '#', :class => 'thumbnail photo-thumbnail', :'data-target' => '#modal', :'data-id' => photo[:id]  do
        = image_tag photo[:thumbnail]
        .caption
          %h5
            = photo[:title]
.modal.hide.fade#modal

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = javascript_include_tag "application"
    %title= content_for?(:title) ? yield(:title) : "DrPicasa"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.brand(href="#") Dr. Picasa
    .container
      .row
        = bootstrap_flash
        = yield

      %footer
        %p &copy; Roman Brodetski 2013